# Generated by Django 4.1.4 on 2022-12-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedPosts', models.ManyToManyField(blank=True, related_name='liked_by', to='project.post')),
            ],
        ),
    ]
