# Generated by Django 4.1.4 on 2022-12-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_profile_likedposts_post_content_post_likedby_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
